### ISSUE TITLE
Duplicate attribute option translations

### ISSUE THREAD

**Issue by roman-snitko-vaimo** [Qordobacode/magento-2#11]
There is an issue with `Qordoba\Connector\Cron\Download::updateAttributeOption()` method.
https://github.com/Qordobacode/magento-2/blob/f3e6bd8cefdf8b48327b802fd6f7287bf9203270/Cron/Download.php#L284
If we add new translation version for product attribute option in Qordoba, Magento downloads the file and creates duplicate option value instead of updating it.

This is caused by this SQL query:
`"SELECT value_id FROM {$tableName} WHERE option_id = :option_id AND store_id = :store_id AND value = :value"`

There is no need to check for `value` here, because new value is different from existing value, and this query will not return anything.

Query should be changed to this one:
`"SELECT value_id FROM {$tableName} WHERE option_id = :option_id AND store_id = :store_id"`

**Comment by RadikChernyshov** [comment]
Thank you for the issue. Will be fixed ASAP.
